# Standards: 1.2
---
# @meta author:value: [Thomas Boerger](https://github.com/tboerger)
# @meta description: >
# [![Source Code](https://img.shields.io/badge/github-source%20code-blue?logo=github&logoColor=white)](https://github.com/rolehippie/dnsmasq)
# [![General Workflow](https://github.com/rolehippie/dnsmasq/actions/workflows/general.yml/badge.svg)](https://github.com/rolehippie/dnsmasq/actions/workflows/general.yml)
# [![Readme Workflow](https://github.com/rolehippie/dnsmasq/actions/workflows/readme.yml/badge.svg)](https://github.com/rolehippie/dnsmasq/actions/workflows/readme.yml)
# [![Galaxy Workflow](https://github.com/rolehippie/dnsmasq/actions/workflows/galaxy.yml/badge.svg)](https://github.com/rolehippie/dnsmasq/actions/workflows/galaxy.yml)
# [![License: Apache-2.0](https://img.shields.io/github/license/rolehippie/dnsmasq)](https://github.com/rolehippie/dnsmasq/blob/master/LICENSE)
# [![Ansible Role](https://img.shields.io/badge/role-rolehippie.dnsmasq-blue)](https://galaxy.ansible.com/rolehippie/dnsmasq)
#
# Ansible role to install and configure dnsmasq DNS caching server.
#
# ## Sponsor
#
# Building and improving this Ansible role have been sponsored by my current and previous employers like **[Cloudpunks GmbH](https://cloudpunks.de)** and **[Proact Deutschland GmbH](https://www.proact.eu)**.
# @end
# @meta dependencies:value: >
# None
# @end
galaxy_info:
  role_name: dnsmasq
  namespace: rolehippie
  author: Thomas Boerger
  description: Ansible role to install and configure dnsmasq DNS caching server
  license: Apache-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - jammy
  galaxy_tags:
    - dns
    - cache

dependencies: []

...
