# tasks file for nginx_php_fpm
---
# INSTALL nginx
  - name: download PGP-key
    get_url:
       url: http://nginx.org/keys/nginx_signing.key
       dest: /etc/nginx_signing.key
 
  - name: install PGP-key
    apt_key:
       file: /etc/nginx_signing.key
       state: present
 
  - name: Add Nginx Repo deb
    apt_repository:
      repo: deb https://nginx.org/packages/mainline/debian/ buster nginx
 
  - name: Add Nginx Repo deb-src
    apt_repository:
      repo: deb-src https://nginx.org/packages/mainline/debian/ buster nginx
 
  - name: Del Nginx-common
    apt:
      name: nginx-common
      state: absent
      force_apt_get: true
 
  - name: Install Nginx 
    apt:
      name: nginx 
      update_cache: yes
      state: latest
      force_apt_get: true
 
  - name: Start Nginx and Enable it on the every boot
    service:
      name: nginx
      state: started
      enabled: yes


  - name: Template a file nginx
    template:
      src: /etc/ansible/playbook/roles/http/templates/default.conf
      dest: /etc/nginx/conf.d/
      owner: root
      group: root
      mode: '0644'

  - name: Template a file index
    template:
      src: /etc/ansible/playbook/roles/http/templates/index.php
      dest: /opt/nginx/ansible/
      owner: root
      group: root
      mode: '0644'
 
  - name: Copy hosts
    copy:
      src: '/etc/ansible/playbook/roles/http/templates/hosts'
      dest: '/etc/hosts'
    loop:
      - /etc/hosts


  - name: restart nginx
    service:
      name: nginx
      state: restarted
      